# Defining function
def pattern_count_uc(text, pattern):
    """Counts the number of times a pattern appears in a given text, including overlapping occurrences."""
    count = 0
    pattern_length = len(pattern)

    # Iterate through text, checking for overlapping occurrences
    for i in range(len(text) - pattern_length + 1):
        if text[i:i + pattern_length] == pattern:
            count += 1

    return count

# Example usage
text3= "ACGTACGTACGT"
pattern3 = "CG"
print(pattern_count_uc(text3, pattern3)) # Output: 3

# Test case (Quiz)
text_quiz = "CCCTCCGTCTGTAACCGTCTGGGCCGTCTGCTGTCCCTTCCGTCTGACCGCATTCTTTCTACCGTCTGACCGTCTGACCGTCTGCCGTCTGTCCGTCTGCCCGTCTGACGGCCGTCTGATCCGTCTGCCGTCTGTCAAGAATTCTCCTCGCCGTCTGACCCCCGTCTGGCATCCCCGTCTGCCGTCTGGGCCGTCTGTCCGTCTGCGCCGTCTGACCGTCTGCCGTCTGACCGTCTGCGCCGTCTGGCCGTCTGAAAGCCGTCTGCAGTATCTCCGTCTGAAGATCCGTCTGCCGTCTGCCGTCTGCACCCCGTCTGTACCGTCTGGACTGTCCGTCTGCCGTCTGGATCCCGTCTGGCCCGTCTGGCCGTCTGCTCCGTCTGCCGTCTGCCGTCTGCATCCGTCTGTCCGTCTGCCGTCTGGCCGTCTGCCGTCTGCCGTCTGCGCGTGCCGTCTGGCCCGTCTGATGGCCGTCTGCCGTCTGCCGTCTGCCCTAAGACCGTCTGACCGTCTGCTACCGTCTGACCTCCCGTCTGTCACAGAGACCCGTCTGTATTCGCCCGTCTGACCCGTCTGCCGTCTGGGAGTCCGTCTGCCGTCTGCTTGCCACACGACCGTCTGCAGGCAACCGTCTGCTGCCGTCTGCCGTCTGCCGTCTGTCCGTCTGCCGTCTGCCCGTCTGCAAGTCAACCCGTCTGCAGCGCTCCGTCTGTCCGTCTGGCTGATCGCCCCGTCTGCCGTCTGCATCCGTCTGCACATTCCGTCTGACCGTCTGTCATTTTGCCGTCTGAGCCGTCTGGCGGGAATCCGTCTGCCGTCTGCAAGTCCGTCTGCCGTCTGCATTCTACCCCGTCTGCGACTAAGACCGTCTGCGCCGTCTGACCCGTCTGGCCGTCTGCCGTCTGCCGTCTGCGACTCCGTCTGAGCCGTCTGGCCGTCTGCCGATCCGTCTGGCCGTCTG"
pattern_quiz = "CCGTCTGCC"
print(pattern_count_uc(text_quiz, pattern_quiz)) # Output: 28

# Test case (Quiz)
text3= "CGTGACAGTGTATGGGCATCTTT"
pattern3 = "TGT"
print(pattern_count_uc(text3, pattern3)) # Output: 1
